#!/bin/bash

read -s -p "Enter certificate storage password: " KSpassword
echo

for file in `ls -1 | grep -i -e "\.pdf$" | grep -i -v _signed.pdf`; do
    echo $file
    java -jar ~/jsignpdf/JSignPdf.jar $file -ksf ~/jsignpdf/keystore.p12 -ksp $KSpassword --img-path ~/jsignpdf/signature.png -lpf ~/.JSignPdf >/dev/null
done
